# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/erpc.yaml.j2

erpc:
  fullnameOverride: erpc
  image:
    repository: docker.ethquokkaops.io/gh/erpc/erpc
    tag: "0.0.33"
    #repository: docker.io/skylenet/erpc
    #tag: fix-chainid-2
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 6
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: rpc.mekong.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  livenessProbe:
    httpGet:
      path: /healthcheck
      port: http
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 30
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /healthcheck
      port: http
    initialDelaySeconds: 10
    periodSeconds: 12
    failureThreshold: 5
    timeoutSeconds: 10
  
  extraEnv:
    - name: "GOGC"
      value: "30"
    - name: "GOMEMLIMIT"
      value: "3GiB"

  serviceMonitor:
    enabled: true
    labels:
      vmagent: common

  config: |
    logLevel: info

    admin:
      auth:
        strategies:
          - type: secret
            secret:
              value: <path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.password}>

    database:
      evmJsonRpcCache:
        connectors:
          - id: memory-cache
            driver: memory
            memory:
              maxItems: 100000
        policies:
          # Cache all methods with finalized data including empty responses
          - network: "*"
            method: "*"
            finality: finalized
            empty: allow
            connector: memory-cache
            ttl: 0
          # Cache unfinalized data only for 5 seconds (getLogs of a recent block) except empty responses
          - network: "*"
            method: "*"
            finality: unfinalized
            empty: ignore
            connector: memory-cache
            ttl: 5s
          # Cache unknown finalization data (eth_trace*) only for 10 seconds
          - network: "*"
            method: "*"
            finality: unknown
            empty: ignore
            connector: memory-cache
            ttl: 10s
          # Cache realtime data only for 2 seconds (eth_blockNumber, eth_gasPrice, etc) to reduce costs yet fresh enough data
          - network: "*"
            method: "*"
            finality: realtime
            empty: ignore
            connector: memory-cache
            ttl: 2s

    server:
      httpHostV4: "0.0.0.0"
      listenV6: true
      httpHostV6: "[::]"
      httpPort: 4000
      aliasing:
        rules:
          - matchDomain: "*"
            serveProject: "main"
            serveArchitecture: "evm"
            serveChain: "7078815900"

    metrics:
      enabled: true
      hostV4: "0.0.0.0"
      hostV6: "[::]"
      port: 4001

    projects:
      - id: main
        networks:
          - architecture: evm
            evm:
              chainId: 7078815900
            failsafe:
              timeout:
                # Network-level timeout applies to the whole lifecycle of the request,
                # this includes retries on network and/or upstream level.
                duration: 20s
              retry:
                # Total retries besides the initial request:
                maxAttempts: 8
                # Min delay between retries:
                delay: 500ms
                # Maximum delay between retries:
                backoffMaxDelay: 10s
                # Multiplier for each retry for exponential backoff:
                backoffFactor: 0.3
                # Random jitter to avoid thundering herd,
                # e.g. add between 0 to 500ms to each retry delay:
                jitter: 500ms
              hedge:
                # Recommended: Use quantile-based hedging, e.g. p99:
                quantile: 0.99
                # This fixed-delay is always added to whatever is the quantile-based delay.
                delay: 0ms
                # Minimum delay to wait before trigger next hedge.
                minDelay: 100ms
                # Maximum delay to wait before trigger next hedge.
                maxDelay: 2s
                # Maximum number of hedges to trigger.
                maxCount: 1
        cors:
          allowedOrigins:
            #- "https://*.ethpandaops.io"
            - "*"
          allowedMethods: 
            - "GET"
            - "POST"
            - "OPTIONS"
          allowedHeaders:
            - "Content-Type"
        upstreamDefaults:
          allowMethods:
            - "eth_blockNumber"
            - "eth_call"
            - "eth_chainId"
            - "eth_estimateGas"
            - "eth_feeHistory"
            - "eth_gasPrice"
            - "eth_getBalance"
            - "eth_getBlockByHash"
            - "eth_getBlockByNumber"
            - "eth_getBlockReceipts"
            - "eth_getBlockTransactionCountByHash"
            - "eth_getBlockTransactionCountByNumber"
            - "eth_getCode"
            - "eth_getFilterChanges"
            - "eth_getLogs"
            - "eth_getStorageAt"
            - "eth_getTransactionByBlockHashAndIndex"
            - "eth_getTransactionByBlockNumberAndIndex"
            - "eth_getTransactionByHash"
            - "eth_getTransactionCount"
            # - "eth_getTransactionReceipt" tmp disable
            - "eth_newBlockFilter"
            - "eth_newPendingTransactionFilter"
            - "eth_maxPriorityFeePerGas"
            - "eth_sendRawTransaction"
            - "eth_subscribe"
            - "eth_syncing"
            - "eth_uninstallFilter"
            - "eth_unsubscribe"
            - "net_listening"
            - "net_version"
            - "rpc_modules"
            - "web3_clientVersion"
            - "debug_getRawReceipts"
            - "debug_traceBlock"
            - "trace_transaction"
            - "trace_block"
        upstreams:
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.grandine-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.grandine-geth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.grandine-nethermind-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-besu-2.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-2.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-geth-10.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-reth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lighthouse-reth-2.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.lodestar-reth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-erigon-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-ethereumjs-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-geth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-geth-2.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-nethermind-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.nimbus-reth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.mekong-devnet-0.ethpandaops.io
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-geth-1.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: full
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-geth-10.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: full
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-geth-11.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: full
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: full
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-nethermind-2.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: full
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-reth-1.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: archive
              chainId: 7078815900
          - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.prysm-reth-2.mekong-devnet-0.ethpandaops.io
            evm: 
              statePollerInterval: 30s
              nodeType: archive
              chainId: 7078815900
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-besu-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-erigon-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-erigon-2.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-geth-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.mekong-devnet-0.ethpandaops.io
        #  - endpoint: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.mekong-devnets.node_ingress.combined}>@rpc.teku-reth-1.mekong-devnet-0.ethpandaops.io
